spring:
  profiles.active: test
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    showSql: true
    hibernate:
      ddl-auto: update
    properties:
        hibernate:
          format_sql: true
          show_sql: true

  springdoc:
    pathsToMatch: /api/sebook/**
    swagger-ui:
      use-root-path: true

  sebook:
    imagens:
      diretorio: classpath:/imagens-livros/
